databases:
  - name: maybe
    user: maybe
    plan: free

services:
  - type: web
    plan: free
    autoDeploy: false
    runtime: ruby
    name: maybe
    repo: https://github.com/maybe-finance/maybe.git
    branch: main
    healthCheckPath: /up
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # We run this in the startCommand instead because `free` plan doesn't allow this option in Blueprint
    startCommand: "bundle exec rails db:migrate && bundle exec rails server"
    envVars:
      - key: SELF_HOSTING_ENABLED
        value: true
      - key: HOSTING_PLATFORM
        value: render
      - key: DATABASE_URL
        fromDatabase:
          name: maybe
          property: connectionString
      # Since the app is self-hosted, we cannot use master.key to encrypt credentials.  App depends entirely on ENV variables
      # https://api.rubyonrails.org/v7.1.3.2/classes/Rails/Application.html#method-i-secret_key_base
      - key: SECRET_KEY_BASE
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
      - key: GOOD_JOB_EXECUTION_MODE
        value: async # Typically, `external` is used in prod, but this avoids another cron service and is generally fine for a self-hoster given low traffic
