shared:
  exchange_rates:
    provider: <%= ENV.fetch "EXCHANGE_RATES_PROVIDER", "synth" %>
    key: <%= ENV.fetch "EXCHANGE_RATES_API_KEY", ENV["SYNTH_API_KEY"] %>
  merchant_data:
    provider: <%= ENV.fetch "MERCHANT_DATA_PROVIDER", "synth" %>
    key: <%= ENV.fetch "MERCHANT_DATA_API_KEY", ENV["SYNTH_API_KEY"] %>
  reale_state_valuations:
    provider: <%= ENV.fetch "REAL_ESTATE_VALUATIONS_PROVIDER", "null" %>
    key: <%= ENV["REAL_ESTATE_VALUATIONS_API_KEY"] %>
