name: Quality

on:
    push:
        branches: ['main']
    pull_request:
        types: [opened, synchronize]

jobs:
    quality:
        name: Quality checks
        timeout-minutes: 15
        runs-on: ubuntu-latest
        # To use Remote Caching, uncomment the next lines and follow the steps below.
        # env:
        #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
        #  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

        steps:
            - name: Check out code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2

            - name: Setup Node.js environment
              uses: actions/setup-node@v3

            - name: Install global turbo
              run: yarn global add turbo

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Run quality checks
              run: turbo run lint check-types
